//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VivLimited2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class equiprentalsubclass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equiprentalsubclass()
        {
            this.equiprentalimagesliders = new HashSet<equiprentalimageslider>();
            this.equipmentreservations = new HashSet<equipmentreservation>();
        }
    
        public short Id { get; set; }
        public string EquipName { get; set; }
        public string Specification { get; set; }
        public Nullable<bool> Available { get; set; }
        public string Cost { get; set; }
        public Nullable<short> EquipRentalMainClassId { get; set; }
        public string ImageUrl { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> DateTimeEdited { get; set; }
    
        public virtual equiprentalmainclass equiprentalmainclass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equiprentalimageslider> equiprentalimagesliders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipmentreservation> equipmentreservations { get; set; }
    }
}
