//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VivLimited2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipmentreservation
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Company { get; set; }
        public string PhoneNumb { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<short> EquipmentCategoryId { get; set; }
        public Nullable<short> EquipmentTypeId { get; set; }
        public string Comments { get; set; }
    
        public virtual equiprentalmainclass equiprentalmainclass { get; set; }
        public virtual equiprentalsubclass equiprentalsubclass { get; set; }
    }
}
