//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VivLimited2._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbo_vivlimitedEntities : DbContext
    {
        public dbo_vivlimitedEntities()
            : base("name=dbo_vivlimitedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<homepageslider> homepagesliders { get; set; }
        public virtual DbSet<pagecontent> pagecontents { get; set; }
        public virtual DbSet<career> careers { get; set; }
        public virtual DbSet<equiprentalmainclass> equiprentalmainclasses { get; set; }
        public virtual DbSet<equiprentalsubclass> equiprentalsubclasses { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<projectpic> projectpics { get; set; }
        public virtual DbSet<equiprentalimageslider> equiprentalimagesliders { get; set; }
        public virtual DbSet<equipmentreservation> equipmentreservations { get; set; }
    }
}
