//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VivLimited2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagecontent
    {
        public sbyte Id { get; set; }
        public string PageTitle { get; set; }
        public string PageText { get; set; }
        public string PageUrl { get; set; }
        public string PageBannerUrl { get; set; }
        public string DefaultPageIconUrl { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> DateTimeEdited { get; set; }
    }
}
