//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VivLimited2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.projectpics = new HashSet<projectpic>();
        }
    
        public short Id { get; set; }
        public string Title { get; set; }
        public string Client { get; set; }
        public string Consultant { get; set; }
        public Nullable<System.DateTime> DateAwarded { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public string Status { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> DateTimeEdited { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projectpic> projectpics { get; set; }
    }
}
